name: explora_cdmx
description: "Una aplicación para explorar la Ciudad de México"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.1

  cupertino_icons: ^1.0.8

  syncfusion_flutter_calendar: any
  flex_color_picker: any
  cupertino_calendar_picker: any

  url_launcher: any
  cached_network_image: any
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  cupertino_calendar_picker: ^2.2.4
  cloud_firestore: ^6.0.2
  flex_color_picker: ^3.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/Icono.png